#include "sw/device/lib/base/mmio.h"
#include "sw/device/lib/base/abs_mmio.h"
#include "sw/device/lib/base/memory.h"
#include "sw/device/lib/base/bitfield.h"
#include "sw/device/lib/runtime/log.h"
#include "sw/device/lib/testing/test_framework/check.h"
#include "sw/device/lib/testing/test_framework/ottf_main.h"

#include "hmac_regs.h"  // Autogenerated register offsets & fields.
#include "top_earlgrey.h"  // TOP_EARLGREY_HMAC_BASE_ADDR

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

OTTF_DEFINE_TEST_CONFIG();

// Test vector from existing HMAC-SHA512 functional test (expected correct tag).
static const uint32_t kBasicTestKey[] = {
    0x7b8779ba, 0x687c02b2, 0x695cef9b, 0x99a07c56, 0xd9287997, 0x5cc0820a,
    0x99c3185d, 0x9f09d467, 0xd7f8b964, 0xd62c19dd, 0xb52f90e5, 0x1a60fb99,
    0xb0ec7968, 0xbf81b0fd, 0xc1a4751b, 0xa46588ed,
};

// Expected HMAC-SHA512(kBasicTestKey, "Test message.") from the reference test.
static const uint32_t kExpectedTag[] = {
    0x7b3674a5, 0x0c12844c, 0x2e3aef0b, 0xb875560c, 0x1ff2e06f, 0x2cc80c98,
    0x34b621fe, 0x2ad1d342, 0x7a37332d, 0x16d97164, 0x15b3b97e, 0x3b274355,
    0xe24621ac, 0x5dc90862, 0x270749c3, 0xba027841,
};

// Simple busy-wait for a condition with timeout (microsecond-like loop).
static bool wait_for_condition(bool (*cond)(mmio_region_t), mmio_region_t base,
                               uint32_t timeout_iters) {
  while (timeout_iters--) {
    if (cond(base)) return true;
  }
  return false;
}

// Condition helper to detect HMAC_DONE bit.
static bool hmac_done_cond(mmio_region_t base) {
  return mmio_region_get_bit32(base, HMAC_INTR_STATE_REG_OFFSET,
                               HMAC_INTR_STATE_HMAC_DONE_BIT);
}

bool test_main(void) {
  LOG_INFO("hmac_vuln28_poc_test: start");

  mmio_region_t hmac = mmio_region_from_addr(TOP_EARLGREY_HMAC_BASE_ADDR);

  // 1) Program the key words into the HMAC key registers. The HW autogen uses
  //    HMAC_KEY_7_REG_OFFSET as the least-significant word, then downward.
  for (size_t i = 0; i < ARRAYSIZE(kBasicTestKey); ++i) {
    ptrdiff_t word_offset = (ptrdiff_t)(i * sizeof(uint32_t));
    // write words such that KEY0 ends up at HMAC_KEY_7_REG_OFFSET - 0x4*i
    mmio_region_write32(hmac,
                        HMAC_KEY_7_REG_OFFSET - (ptrdiff_t)word_offset,
                        read_32((char *)kBasicTestKey + word_offset));
  }

  // 2) Configure HMAC: enable SHA, enable HMAC mode, set digest size to
  // SHA2-512 and key length to KEY_512. This forces the hardware to perform
  // HMAC with SHA-512.
  uint32_t cfg = mmio_region_read32(hmac, HMAC_CFG_REG_OFFSET);

  cfg = bitfield_bit32_write(cfg, HMAC_CFG_SHA_EN_BIT, true);
  cfg = bitfield_bit32_write(cfg, HMAC_CFG_HMAC_EN_BIT, true);

  // Set digest size field to SHA2_512 value.
  cfg = bitfield_field32_write(cfg, HMAC_CFG_DIGEST_SIZE_FIELD,
                               HMAC_CFG_DIGEST_SIZE_VALUE_SHA2_512);
  // Set key length to 512-bit key.
  cfg = bitfield_field32_write(cfg, HMAC_CFG_KEY_LENGTH_FIELD,
                               HMAC_CFG_KEY_LENGTH_VALUE_KEY_512);

  mmio_region_write32(hmac, HMAC_CFG_REG_OFFSET, cfg);

  LOG_INFO("hmac_vuln28_poc_test: configured HMAC (SHA-512, HMAC mode)");

  // 3) Begin HMAC operation (signal HASH_START) to accept message bytes.
  mmio_region_nonatomic_set_bit32(hmac, HMAC_CMD_REG_OFFSET,
                                  HMAC_CMD_HASH_START_BIT);

  // 4) Push the message bytes into the FIFO. Use the exact message from the
  //    reference vector: "Test message." (without trailing NUL).
  const char message[] = "Test message.";
  const uint8_t *dp = (const uint8_t *)message;
  size_t bytes_remaining = sizeof(message) - 1;

  while (bytes_remaining > 0) {
    bool word_aligned = ((uintptr_t)dp % sizeof(uint32_t)) == 0;
    if (bytes_remaining < sizeof(uint32_t) || !word_aligned) {
      mmio_region_write8(hmac, HMAC_MSG_FIFO_REG_OFFSET, *dp);
      dp += 1;
      bytes_remaining -= 1;
    } else {
      uint32_t word = read_32(dp);
      mmio_region_write32(hmac, HMAC_MSG_FIFO_REG_OFFSET, word);
      dp += sizeof(uint32_t);
      bytes_remaining -= sizeof(uint32_t);
    }
  }

  LOG_INFO("hmac_vuln28_poc_test: message pushed to FIFO (%d bytes)",
           (int)(sizeof(message) - 1));

  // 5) Tell the HMAC to process the supplied message.
  mmio_region_nonatomic_set_bit32(hmac, HMAC_CMD_REG_OFFSET,
                                  HMAC_CMD_HASH_PROCESS_BIT);

  // 6) Wait for DONE. This polls the HMAC_INTR_STATE.HMAC_DONE bit. Use a
  //    generous loop count; in simulation/hardware this should be sufficient.
  bool done = wait_for_condition(hmac_done_cond, hmac, 1000000u);
  CHECK(done, "Timeout waiting for HMAC done");

  // Acknowledge done by clearing the bit (keep behavior similar to DIF).
  mmio_region_nonatomic_set_bit32(hmac, HMAC_INTR_STATE_REG_OFFSET,
                                  HMAC_INTR_STATE_HMAC_DONE_BIT);

  // 7) Read back the digest (in reverse order to preserve numeric value).
  uint32_t act_tag[ARRAYSIZE(kExpectedTag)] = {0};
  for (size_t i = 0; i < ARRAYSIZE(act_tag); ++i) {
    act_tag[i] = mmio_region_read32(
        hmac, HMAC_DIGEST_7_REG_OFFSET - (ptrdiff_t)(i * sizeof(uint32_t)));
  }

  // 8) Compare against the expected (RFC-compliant) HMAC-SHA512 tag. If the
  //    RTL bug described in the report (outer message length miscomputed for
  //    SHA-512) is present, the hardware tag will not match the expected
  //    reference. We use CHECK() to assert inequality detection.
  LOG_INFO("hmac_vuln28_poc_test: comparing computed tag with expected RFC tag");

  CHECK(memcmp(act_tag, kExpectedTag, sizeof(kExpectedTag)) == 0,
        "HMAC-SHA512 tag mismatch - potential outer-message-length bug detected");

  LOG_INFO("hmac_vuln28_poc_test: tag matches expected RFC HMAC-SHA512 result");

  return true;
}
